config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#index'
  resources :homes
  resources :plans
  resources :services
  resources :installs
  resources :actives
  resources :abouts
  resources :infos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/info.rb
class Info < ApplicationRecord
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController

  def index
    @sites='about'
  end

end

app/controllers/actives_controller.rb
class ActivesController < ApplicationController

  def index
    @sites='active'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @sites='home'
  end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  def index
    @sites='info'
  end
end

app/controllers/installs_controller.rb
class InstallsController < ApplicationController

  def index
    @sites='install'
  end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  @sites='plan'
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def index
    @sites='service'
  end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/actives_helper.rb
module ActivesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/installs_helper.rb
module InstallsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/abouts/index.html.erb
<%= render 'layerbegin' %>

<div class="container">

</div>


<%= render 'layerend' %>

app/views/actives/index.html.erb
<%= render 'layerbegin' %>

<div class="container">

</div>


<%= render 'layerend' %>

app/views/application/_layerbegin.html.erb
<style>
    .navbar-brand {
        width: 110px;
        height: auto;
        padding: 7.5px 15px;
    }
    .navbar-brand__img {
        width: 100%;
    }
    .navbar-toggle {
        margin-top: 17px;
        margin-bottom: 17px;
    }
    .navbar-collapse>ul>li>a {
        display: inline-block;
        height: 82px;
        text-align: center;
        font-size: 16px;
        text-decoration: none;
        color: #fff;
        vertical-align: top;
        margin: 0 21px;
        padding: 30px 10px 10px 5px;
        position: relative;
    }
    .nav > li > a:hover, .nav > li > a:focus {
        text-decoration: none;
        background-color: inherit;
        color: #0081cc;
    }
    .active {
        color: #0081cc;
    }
</style>
<nav class="navbar navbar-fixed-top  navbar-without-shadow" style="background-color: rgba(0,0,0,0.7);">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" >
        <span class="sr-only">导航</span>
        <span class="icon-bar" style="background: #fff;"></span>
        <span class="icon-bar" style="background: #fff;"></span>
        <span class="icon-bar" style="background: #fff;"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag 'liushushu_logo_web.png',class:"navbar-brand__img"%>
      </a>
    </div>

    <div class="navbar-collapse collapse" id="navbar-collapse" aria-expanded="false" style="height: 1px;">
      <ul class="nav navbar-nav navbar-right">
        <% if @sites == 'home' %>
            <li>
              <%= link_to '首页',homes_path,class:'active' %>
            </li>
        <% else %>
            <li>
              <%= link_to '首页',homes_path %></li>
        <% end %>
        <% if @sites == 'info' %>
            <li>
              <%= link_to '最新资讯',infos_path,class:'active' %></li>
        <% else %>
            <li>
              <%= link_to '最新资讯',infos_path %></li>
        <% end %>
        <% if @sites == 'install' %>
            <li>
              <%= link_to '工程案例',installs_path,class:'active' %></li>
        <% else %>
            <li>
              <%= link_to '工程案例',installs_path %></li>
        <% end %>
        <% if @sites == 'service' %>
            <li>
              <%= link_to '用户中心',services_path,class:'active' %></li>
        <% else %>
            <li>
              <%= link_to '用户中心',services_path %></li>
        <% end %>
        <% if @sites == 'active' %>
            <li>
              <%= link_to '关于我们',actives_path,class:'active' %></li>
        <% else %>
            <li>
              <%= link_to '关于我们',actives_path %></li>
        <% end %>
        <% if @sites == 'about' %>
            <li>
              <%= link_to '帮助中心',abouts_path,class:'active' %></li>
        <% else %>
            <li>
              <%= link_to '帮助中心',abouts_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/application/_layerend.html.erb
<footer class="footer navbar-fixed-bottom">
  <div class="f-btm">
    <div class="container">
      <div class="copyright text-center">
        <span>&copy; 2017 刘叔叔版权所有</span>

      </div>
    </div><!-- w1200 end -->
  </div>
</footer>

app/views/homes/index.html.erb
<style>
    .navbar-brand {
        width: 110px;
        height: auto;
        padding: 7.5px 15px;
    }
    .navbar-brand__img {
        width: 100%;
    }
    .navbar-toggle {
        margin-top: 17px;
        margin-bottom: 17px;
    }
    .navbar-collapse>ul>li>a {
        display: inline-block;
        height: 82px;
        text-align: center;
        font-size: 16px;
        text-decoration: none;
        color: #fff;
        vertical-align: top;
        margin: 0 21px;
        padding: 30px 10px 10px 5px;
        position: relative;
    }
    .nav > li > a:hover, .nav > li > a:focus {
        text-decoration: none;
        background-color: inherit;
        color: #0081cc;
    }
    .active {
        color: #0081cc;
    }
</style>
<nav class="navbar navbar-fixed-top  navbar-without-shadow" style="background-color: rgba(0,0,0,0.7);">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" >
        <span class="sr-only">导航</span>
        <span class="icon-bar" style="background: #fff;"></span>
        <span class="icon-bar" style="background: #fff;"></span>
        <span class="icon-bar" style="background: #fff;"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag 'liushushu_logo_web.png',class:"navbar-brand__img"%>
      </a>
    </div>

    <div class="navbar-collapse collapse" id="navbar-collapse" aria-expanded="false" style="height: 1px;">
      <ul class="nav navbar-nav navbar-right">
        <% if @sites == 'home' %>
            <li>
              <%= link_to '首页',homes_path,class:'active' %>
            </li>
        <% else %>
            <li>
              <%= link_to '首页',homes_path %></li>
        <% end %>
        <% if @sites == 'info' %>
            <li>
              <%= link_to '最新资讯',infos_path,class:'active' %></li>
        <% else %>
            <li>
              <%= link_to '最新资讯',infos_path %></li>
        <% end %>
        <% if @sites == 'install' %>
            <li>
              <%= link_to '工程案例',installs_path,class:'active' %></li>
        <% else %>
            <li>
              <%= link_to '工程案例',installs_path %></li>
        <% end %>
        <% if @sites == 'service' %>
            <li>
              <%= link_to '用户中心',services_path,class:'active' %></li>
        <% else %>
            <li>
              <%= link_to '用户中心',services_path %></li>
        <% end %>
        <% if @sites == 'active' %>
            <li>
              <%= link_to '关于我们',actives_path,class:'active' %></li>
        <% else %>
            <li>
              <%= link_to '关于我们',actives_path %></li>
        <% end %>
        <% if @sites == 'about' %>
            <li>
              <%= link_to '帮助中心',abouts_path,class:'active' %></li>
        <% else %>
            <li>
              <%= link_to '帮助中心',abouts_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

<div id="fullDiv">
  <div id="side">
    <ul id="menu">
      <li data-menuanchor="w1" class="active" ><a class="a1" href="#w1" title="刘叔叔">1</a></li>
      <li data-menuanchor="w2"><a class="a2" href="#w2" title="服务模式">2</a></li>
      <li data-menuanchor="w3"><a class="a3" href="#w3" title="我们的优势">3</a></li>
      <li data-menuanchor="w4"><a class="a4" href="#w4" title="互联网家居售后3.0">4</a></li>
      <li data-menuanchor="w5"><a class="a5" href="#w5" title="用户心声">5</a></li>

    </ul>
  </div>

  <div class="section section1">
    <div class="s1-bg"></div>
    <div class="s1-con" style="width: 80%;max-width: 800px;" >
      <div class="s1-txt" style="width: 100%" ><img style="width: 100%" src="../image/txt.png" alt="家居配送、安装、维修、返货直接找万师傅"></div>
      <div class="s1-btn">

      </div>
    </div><!-- s1-con end -->
  </div>
  <div class="section section2">

    <div id="s2-wrap-top">
      <div class="s2-bg-btm-wrap"><div class="s2-bg-top"></div></div>
      <div class="s2-top">
        <div class="topleft"></div>
        <div class="topright" style="padding-left: 10%;">
          <div class="s2-null"></div>
          <p class="t1" style="width: 90%;max-width: 550px;"><img style="width: 100%;" src="../image/t1.png" alt="让用户自由选择"/></p>
          <p class="ts1" style="width: 90%;max-width: 600px;"><img style="width: 100%;" src="../image/ts1.png" alt="一个订单多个师傅报价，任意挑选"/></p>
        </div>
      </div>
    </div>

    <div id="s2-wrap-btm">
      <div class="s2-bg-btm-wrap"><div class="s2-bg-btm"></div></div>
      <div class="s2-btm">
        <div class="btmleft" style="padding-left: 10%;">
          <div class="s2-null"></div>
          <p class="t2" style="width: 90%;max-width: 600px;"><img style="width: 100%;" src="../image/t2.png" alt="让师傅自主经营"/></p>
          <p class="ts2" style="width: 90%;max-width: 600px;"><img style="width: 100%;" src="../image/ts2.png" alt="告别派单模式，师傅自由报价接单"/></p>
        </div>
        <div class="btmright"></div>
      </div>
    </div>
  </div>

  <div class="section section3">
    <div class="s3-bg"></div>
    <div class="t1">
      <img src="http://frontend.wanshifu.com/www/html/wan/images/sec3/you.png" alt="我们的优势">
    </div>
    <div class="btm">
      <div class="s3-item">
        <div class="service">
          <ul>
            <li class="ser1"><img src="../image/s3t1.png"/><p class="ser-txt" style="color: #fff;">拥有百位经验丰富师傅<br/>让你有更多选择</p></li>
            <li class="ser2"><img src="../image/s3t2.png"/><p class="ser-txt" style="color: #fff;min-width: 240px;">只需要下单，师傅上门安装</p></li>
            <li class="ser3" style="padding-left: 100px;"><img src="../image/s3t3.png"/><p class="ser-txt" style="color: #fff;">不需监督，安装让你放心，避免出行不便</p></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="section section4" >
    <div class="s4-bg"></div>
    <div class="s4-con" style="width: 100%;max-width: 700px;">
      <div class="s4-top-layout">
        <p class="shield"><img style="width: 100%;" src="../image/sc4tt.png"/></p>
        <p class="pro-service"><img style="width: 100%;" src="../image/service.png"/></p>
        <p class="pro-more"></p>
      </div>
      <div class="safe" style="width: 100%;">
        <ul>
          <li class="ser1">
            <img src="../image/s3c1.png"><img src="../image/s4t1.png"/>
            <p class="ser-txt">我们只为让你放心 为安全提供保障</p>
          </li>
          <li class="ser2">
            <img src="../image/s3c2.png"><img src="../image/s4t2.png"/>
            <p class="ser-txt">诚信担保从下单到完工全程担保</p>
          </li>
        </ul>
      </div>
    </div><!-- s4-con end -->
  </div>

  <div class="section section5">
    <!--<p class="u-voice"><img src="http://frontend.wanshifu.com/www/html/wan/images/sec5/voice.png"></p>-->
    <div class="btm">
      <div class="service">
        <div class="slide">
          <div class="feedback">
            <div class="slidewraphead"><div id="slidehead" class="cir">

            </div></div>


            <div class="slidewrappos pos"><div id="slidepos">

            </div></div>
            <!--<img class="quotel" src="http://frontend.wanshifu.com/www/html/wan/images/sec5/ql.png">-->
            <!--<img class="quoter" src="http://frontend.wanshifu.com/www/html/wan/images/sec5/qr.png">-->
            <div class="slidewraptext text"><div id="slidetext">

            </div></div>
            <div class="slideleft"></div>
            <div class="slideright"></div>
          </div><!-- feedback -->
        </div>
      </div>
    </div>
  </div>



    <footer>
      <div class="f-btm">
        <div class="w1200">
          <div class="copyright">
            <span>&copy; 2017 刘叔叔版权所有</span>

          </div>
        </div><!-- w1200 end -->
      </div>

    </footer>  </div><!-- section6 end -->
  <!--
  <div class="section section7">
    <h2 style="color:#ccc">section7</h2>
  </div>

  <div class="section section8">
    <h2 style="color:#369">section8</h2>
  </div>
  -->
</div><!-- full END -->
<script>
    $(function () {
        $(".s1-item span").click(function(){
            var cat=$(this).attr('rel');
            var newhref='http://www.wanshifu.com/orders/task/publish?cat='+cat;
            $('#order-master').attr('href',newhref);
        });
    })
</script>    <!--页脚-->
<ul class="float-menu">
  <li class="new-order">
    <a href="http://www.wanshifu.com/orders/task/publish">
      <ul>
        <li><h3>任务发布后</h3><p>3分钟内收到师傅报价</p></li>
        <li><h3>每个任务</h3><p>平均5个报价可选择</p></li>
        <li><h3>全国99%的地区</h3><p>任务得到完美解决</p></li>
      </ul>
    </a>
  </li>
  <li class="online-service"><a class="g-fix-middle_zx"></a></li>
</ul>
<!--页脚 End-->

app/views/infos/index.html.erb
<%= render 'layerbegin' %>

<div class="container">

</div>


<%= render 'layerend' %>

app/views/installs/index.html.erb
<%= render 'layerbegin' %>

<div class="container">

</div>


<%= render 'layerend' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lsf</title>

    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no" />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plans/index.html.erb
<%= render 'layerbegin' %>

<div class="container">

</div>


<%= render 'layerend' %>

app/views/services/index.html.erb
<%= render 'layerbegin' %>

<div class="container">

</div>


<%= render 'layerend' %>